services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
